name: Henry
favicon: null
layout_spectrum: 0.5170163314323872
typography_spectrum: 0.533429529517889
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.2683876908849925
  lightness: 0.3814698723144829
  saturation: 0.6711450102739036
  rhythmicContrast: 0.8946932477410883
purpose: []
